/**
 * Additional original CDL practice questions (Air Brakes, Combination, endorsements).
 * Not actual DMV / FMCSA exam items.
 */
import type { SeedQuestion } from "./epa-608";

const A = "air-brakes";
const C = "combination-vehicles";
const H = "hazardous-materials";
const N = "tanker";
const P = "passenger";

const q = (
  category: string,
  prompt: string,
  options: [string, string, string, string],
  correctIndex: 0 | 1 | 2 | 3,
  explanation: string,
  extra: Partial<Omit<SeedQuestion, "category" | "prompt" | "options" | "explanation">> = {},
): SeedQuestion => ({
  category,
  prompt,
  options: options.map((text, i) => ({ label: "ABCD"[i], text, correct: i === correctIndex })),
  explanation,
  difficulty: "MEDIUM",
  isFree: true,
  ...extra,
});

export const moreCdlQuestions: SeedQuestion[] = [
  // ------------------------------------------------------------------ AIR BRAKES
  q(
    A,
    "Air brake systems use compressed air to:",
    [
      "Steer the front axle",
      "Apply the service brakes when you press the pedal",
      "Cool the engine instead of coolant",
      "Inflate the trailer tires from the cab",
    ],
    1,
    "The service brakes are air-applied. Steering is hydraulic or electric power assist, not the air-brake system. Spring (parking) brakes work the opposite way: they apply when air is released.",
    { difficulty: "EASY", tags: ["air-brakes"] },
  ),
  q(
    A,
    "A dual air-brake system means:",
    [
      "Two complete air systems, usually split front and rear, so a leak in one still leaves you some brakes",
      "You must press the pedal twice for every stop",
      "The truck has both air and hydraulic brakes on every wheel",
      "ABS is installed on the trailer only",
    ],
    0,
    "Modern CMVs have two air circuits. If one fails, the other can still stop the vehicle — not as well, but you are not on zero brakes. It is not a double-pump pedal.",
    { tags: ["air-brakes"] },
  ),
  q(
    A,
    "The low-air warning (buzzer, light or both) must come on before pressure falls below:",
    ["20 psi", "40 psi", "60 psi", "100 psi"],
    2,
    "The warning is required at or above 60 psi. If it does not come on in a test, the vehicle is not safe to drive. Waiting until 20 psi is how spring brakes drag on and you lose remaining air.",
    { tags: ["air-brakes", "numbers"] },
  ),
  q(
    A,
    "Spring brakes (parking / emergency) apply when:",
    [
      "You honk the horn",
      "Air pressure is lost or you pull the parking-brake control",
      "The engine is above 2,000 rpm",
      "ABS activates",
    ],
    1,
    "Big springs hold the brakes on. Air pressure holds those springs back for driving. Lose air, or pull the yellow parking knob, and the springs apply. That is why a major leak eventually stops the truck.",
    { difficulty: "EASY", tags: ["air-brakes"] },
  ),
  q(
    A,
    "Compared with hydraulic brakes, air brakes add extra stopping distance mainly because of:",
    [
      "Brake lag — time for air to flow to the chambers",
      "The driver sitting farther from the pedal",
      "ABS always adding a second",
      "Federal law requiring a 3-second pause",
    ],
    0,
    "Air has to travel through lines and valves. That lag is roughly half a second or more on a combination, which is why following distance and speed discipline matter more than in a car.",
    { tags: ["air-brakes"] },
  ),
  q(
    A,
    "Air tanks should be drained:",
    [
      "Once a year at inspection",
      "Regularly (often daily on tanks with manual drains) because oil and water collect at the bottom",
      "Only in summer",
      "Never — moisture helps lubrication",
    ],
    1,
    "Compressors pump water and oil into the tanks. Water freezes valves in winter and takes up space that should be air. Manual petcocks get a daily drain; automatic drains still need a check.",
    { tags: ["air-brakes", "inspection"] },
  ),
  q(
    A,
    "An alcohol evaporator in the air system:",
    [
      "Replaces the need to drain tanks",
      "Helps reduce ice in cold weather but is not a substitute for draining moisture",
      "Is the same as diesel exhaust fluid",
      "Is only used on passenger cars",
    ],
    1,
    "Alcohol evaporators are a cold-weather aid against ice in the lines. They do not remove the water sitting in the tanks. You still drain.",
    { tags: ["air-brakes"], isFree: false },
  ),
  q(
    A,
    "If a manual slack adjuster has too much travel (often more than about one inch at the push rod), the brake:",
    [
      "Is over-adjusted and will drag",
      "May not apply with full force — the brake is out of adjustment",
      "Has ABS failure only",
      "Will automatically fix itself on the next hill",
    ],
    1,
    "Excess stroke means the S-cam has not turned far enough. Stopping power drops and the brake can fade sooner. Automatic adjusters that keep growing in travel still need shop attention — you do not keep twisting them on the yard.",
    { tags: ["air-brakes", "slack"] },
  ),
  q(
    A,
    "During a typical applied-pressure leakage test, a combination vehicle should not lose more than about:",
    ["1 psi in 5 minutes", "3 psi in one minute", "10 psi in one minute", "20 psi in one minute"],
    1,
    "A common standard is no more than 3 psi in one minute for a combination with the brakes applied, and 2 psi for a single vehicle. More leak than that and you find the fitting before you roll.",
    { tags: ["air-brakes", "numbers"] },
  ),
  q(
    A,
    "The air compressor governor typically cuts out (stops pumping) around:",
    ["60 psi", "80 psi", "100 psi", "125 psi (often in the 120–140 range)"],
    3,
    "Governors usually cut out near 125 psi and cut back in near 100 psi. If cut-out is much higher you risk popping a relief valve; if it never builds, you do not have brakes.",
    { tags: ["air-brakes"] },
  ),
  q(
    A,
    "If the ABS lamp on a tractor stays on after the bulb-check, you should:",
    [
      "Refuse to drive because you have no brakes at all",
      "Know that regular brakes still work but ABS may not — have it serviced, and drive as if you do not have ABS",
      "Pump the pedal twice to reset it",
      "Pull the parking brake while moving to clear the lamp",
    ],
    1,
    "ABS is an add-on to the foundation brakes. A dead ABS lamp is not a dead truck, but you lose the anti-lock function and you should get it repaired. Foundation brakes still stop the vehicle.",
    { tags: ["abs"] },
  ),
  q(
    A,
    "Stab braking (without ABS) means:",
    [
      "Holding the pedal on the floor until you stop",
      "Applying hard, releasing as wheels lock, then applying again as they roll",
      "Using only the trailer hand valve",
      "Tapping the parking knob",
    ],
    1,
    "Stab braking is a non-ABS technique: hard apply, release when locked, re-apply. With ABS you do not do this — you brake firmly and steer. Using the trolley valve to stop a moving combination can jackknife the trailer.",
    { tags: ["air-brakes"], isFree: false },
  ),
  q(
    A,
    "Brake fade on a long downgrade is usually caused by:",
    [
      "Brakes getting too cold",
      "Overheating from riding the service brakes instead of using a low gear",
      "Too much air in the tanks",
      "ABS cycling on dry pavement",
    ],
    1,
    "Heat glazes linings and drums expand away from the shoes. The pedal still goes down, but stopping power is gone. Low gear and engine braking prevent the fade that riding the pedal creates.",
    { tags: ["air-brakes", "mountain"] },
  ),
  q(
    A,
    "The trailer hand valve (trolley / Johnson bar) is intended for:",
    [
      "Parking the combination overnight",
      "Testing trailer brakes or a gentle apply — not as a parking brake and not as your only service brake",
      "Releasing spring brakes on the tractor",
      "Turning ABS on",
    ],
    1,
    "Air can leak off if you leave a combination held only by the trailer hand valve. Use the parking-brake control (spring brakes) and wheel chocks. In motion, relying on the trolley can swing the trailer.",
    { tags: ["air-brakes", "combination"] },
  ),
  q(
    A,
    "Front-brake limiting valves (older tractors) in the \"slippery\" position:",
    [
      "Are recommended whenever it rains",
      "Reduce front braking and can make a stop longer — many trainers say to leave them in the normal position",
      "Apply extra front brake for ice",
      "Only work on buses",
    ],
    1,
    "The old idea was to keep the front wheels rolling on ice. In practice you need those front brakes. Modern guidance is not to use the slippery setting; newer trucks often omit the valve.",
    { tags: ["air-brakes"], isFree: false },
  ),
  q(
    A,
    "If air pressure will not build after a reasonable time with the engine at operating rpm, you should:",
    [
      "Drive slowly to the next shop while pumping the pedal",
      "Not drive — without air you will not have reliable service brakes",
      "Disconnect the trailer glad hands and go bobtail",
      "Fill the tanks from a tire inflator",
    ],
    1,
    "No build-up means a compressor, governor, or massive leak problem. Bobtailing does not fix a dead compressor. Do not leave the yard.",
    { difficulty: "EASY", tags: ["air-brakes"] },
  ),

  // ------------------------------------------------------------------ COMBINATION
  q(
    C,
    "Off-tracking means:",
    [
      "The trailer has no ABS",
      "The rear wheels follow a shorter path than the front in a turn, so the trailer cuts the corner",
      "The tractor is wandering in a straight line",
      "You are over the speed limit",
    ],
    1,
    "Longer wheelbase and more articulation increase off-tracking. You compensate by going farther into the intersection before turning so the trailer does not climb the curb.",
    { difficulty: "EASY", tags: ["combination"] },
  ),
  q(
    C,
    "A tractor jackknife is typically caused by:",
    [
      "The trailer passing the tractor as the tractor skids (drive wheels lock or lose traction)",
      "Too much air in the trailer tanks",
      "Using turn signals",
      "Having the fifth wheel too close to the rear tractor axle always",
    ],
    0,
    "When tractor drive wheels lock or the tractor brakes harder than the trailer, the tractor can spin and fold. Trailer-swing is the opposite fold. Empty trailers and slick roads make both more likely.",
    { tags: ["combination", "skid"] },
  ),
  q(
    C,
    "Rearward amplification (\"crack the whip\") is worst with:",
    [
      "A bobtail tractor",
      "Doubles or triples making a sudden steer — the last trailer swings more than the first",
      "A loaded tanker on a straight dry highway",
      "A bus with ABS",
    ],
    1,
    "Each hinge multiplies a quick steering input. That is why doubles/triples have a separate T endorsement and why you do not yank the wheel on a set of pups.",
    { tags: ["combination"] },
  ),
  q(
    C,
    "After coupling, you should pull ahead gently against the trailer brakes (tug test) to confirm:",
    [
      "The fuel tanks are full",
      "The fifth-wheel jaws are locked on the kingpin",
      "ABS is programmed",
      "The trailer height is at maximum",
    ],
    1,
    "Visual checks (no gap, jaws around the shank, locking lever seated, safety latch) plus a tug test catch a missed hook. Landing gear still has to come up after you know it is locked.",
    { difficulty: "EASY", tags: ["coupling"] },
  ),
  q(
    C,
    "The emergency (supply) air line on a trailer is the line that:",
    [
      "Only sounds the horn",
      "Charges the trailer tanks and applies the trailer spring brakes if it breaks or is disconnected",
      "Is optional on Class A",
      "Operates the windshield wipers",
    ],
    1,
    "Lose the red/supply line and the trailer emergency brakes apply. The blue/service line applies the service brakes when you press the pedal. Crossed glad hands give you strange brake behavior — check colors and glad-hand keys.",
    { tags: ["coupling", "air-brakes"] },
  ),
  q(
    C,
    "Glad hands connect:",
    [
      "Electrical trailer lights only",
      "Tractor and trailer air lines",
      "The fifth-wheel jaws",
      "The landing-gear crank",
    ],
    1,
    "Glad hands are the air-line couplers. The seven-way connector is electrical. Mixing them up is a new-driver mistake on the written test and on the yard.",
    { difficulty: "EASY", tags: ["coupling"] },
  ),
  q(
    C,
    "When coupling, trailer height should be:",
    [
      "As high as the landing gear will go so you slide under easily",
      "Low enough that the tractor fifth wheel lifts the trailer slightly as you back under",
      "Irrelevant if you tug-test",
      "Set after you are already locked",
    ],
    1,
    "Too high and the kingpin can miss the jaws (false couple). Too low and you smash the fifth-wheel or the nose of the trailer. You want a light lift as the apron meets the fifth wheel.",
    { tags: ["coupling"] },
  ),
  q(
    C,
    "Backing a combination is safer when you:",
    [
      "Rely only on convex mirrors and never get out",
      "Turn the steering wheel in the direction you want the trailer to go (for a conventional tractor) and use a helper when anyone is around",
      "Jack the wheel the opposite way of a car",
      "Rev high so the trailer climbs curbs",
    ],
    1,
    "For a standard tractor-semitrailer, you steer toward the desired trailer path (then follow with the tractor). Get out and look; use a spotter. Guessing in a blind dock is how doors get torn off.",
    { tags: ["backing"] },
  ),
  q(
    C,
    "The trailer hand valve should not be used to hold a parked combination because:",
    [
      "It is illegal to touch it",
      "Air can leak away and the trailer can roll",
      "It drains the fuel tanks",
      "It disables the tractor ABS permanently",
    ],
    1,
    "The trolley valve is air. Air leaks. Spring parking brakes and chocks are what hold a set overnight.",
    { tags: ["combination", "air-brakes"] },
  ),
  q(
    C,
    "On a right turn with a long trailer, you usually need to:",
    [
      "Hug the curb from the start so cars do not sneak in",
      "Take a wider path with the tractor so the trailer does not climb the curb (without swinging into another lane unsafely)",
      "Stop in the crosswalk and jackknife on purpose",
      "Accelerate to reduce off-tracking",
    ],
    1,
    "Off-tracking pulls the trailer inside the tractor's path. Starting too close to the curb puts duals on the sidewalk. You still cannot swing into occupied lanes — wait, then take the space you need.",
    { tags: ["combination"] },
  ),
  q(
    C,
    "If the trailer supply line disconnects on the highway, you should expect:",
    [
      "Nothing — the trailer will freewheel",
      "The trailer emergency brakes to apply",
      "Only the tractor to lose power steering",
      "The engine to shut down",
    ],
    1,
    "A broken supply (emergency) line dumps trailer tank air and the trailer springs apply. Get off the road safely; do not drag a locked trailer for miles.",
    { tags: ["combination"], isFree: false },
  ),
  q(
    C,
    "Landing gear should be fully raised after coupling because:",
    [
      "It looks neater for DOT",
      "Down or halfway gear can strike pavement, railroad tracks or a dock and damage the trailer",
      "It charges the air tanks faster",
      "It is required only for hazmat",
    ],
    1,
    "Low landing gear is a classic post-hook miss. Raise it, stow the crank, and look before you pull out.",
    { difficulty: "EASY", tags: ["coupling"] },
  ),

  // ------------------------------------------------------------------ HAZMAT
  q(
    H,
    "There are how many DOT hazardous-materials hazard classes?",
    ["3", "7", "9", "16"],
    2,
    "Classes 1 through 9: explosives, gases, flammable liquids, flammable solids, oxidizers, poisons, radioactive, corrosives, miscellaneous. Knowing the class on the shipping paper is how you pick placards and segregation.",
    { difficulty: "EASY", tags: ["hazmat"] },
  ),
  q(
    H,
    "While driving, hazardous-materials shipping papers must be:",
    [
      "In the trailer with the freight",
      "Within immediate reach — typically on the driver's seat when out of the vehicle, or in a pouch on the driver's door / in the cab while driving",
      "Mailed to PHMSA before each trip",
      "Optional if placards are displayed",
    ],
    1,
    "Emergency responders have to find the papers in a standard place. Buried in a duffel in the sleeper does not count. Placards do not replace papers.",
    { tags: ["hazmat"], source: "phmsa-hazmat" },
  ),
  q(
    H,
    "Placards, when required, are displayed:",
    [
      "Only on the rear bumper",
      "On both sides and both ends of the vehicle (four placards)",
      "Inside the cab window",
      "Only if the shipper remembers to include them",
    ],
    1,
    "Four-sided placarding is the standard so police and fire can identify the load from any approach. The shipper provides information; the driver is still responsible for the vehicle leaving with the right diamonds showing.",
    { tags: ["hazmat"] },
  ),
  q(
    H,
    "Near a placarded load of flammables or explosives, you should not:",
    [
      "Use reflective triangles if you break down",
      "Smoke or use flares / burning fusees",
      "Keep a fire extinguisher charged",
      "Park 300 feet from a bridge if the rules require it",
    ],
    1,
    "Open flame next to Class 1 or flammable vapor is how terminals explode. Use triangles, not flares. Smoking distances are in the regulations for a reason.",
    { tags: ["hazmat"] },
  ),
  q(
    H,
    "If you discover a leak in a hazardous-materials load after you are rolling, you should:",
    [
      "Finish the delivery then call the shipper",
      "Park safely, keep people away, notify emergency responders and the carrier — do not continue driving a leaking load",
      "Open all doors to ventilate at highway speed",
      "Dump the product in a ditch",
    ],
    1,
    "A leaking CMV is an emergency, not a late load. Isolation, notifications, and the emergency-response information on the papers are the job — not improvising a drain.",
    { tags: ["hazmat"] },
  ),
  q(
    H,
    "The H (hazmat) endorsement on a CDL also requires:",
    [
      "A TSA security threat assessment (background check)",
      "A college chemistry degree",
      "Only the tanker test",
      "No extra step beyond the knowledge test",
    ],
    0,
    "After 9/11, the H endorsement is not just a written test. TSA vets the driver. Fingerprints and a fee are part of the process; processing can take weeks, so do not book a hazmat job for next Monday.",
    { difficulty: "EASY", tags: ["hazmat"] },
  ),
  q(
    H,
    "Who certifies that a hazmat shipment is properly named, packed and labeled on the shipping paper?",
    [
      "The delivering driver, always, with no shipper role",
      "The shipper (and the carrier/driver still must not accept an obvious violation)",
      "FMCSA headquarters",
      "The fuel desk",
    ],
    1,
    "The shipper's certification is on the paper. Drivers still do not roll with damaged packages, missing placards, or papers that do not match the load.",
    { tags: ["hazmat"], source: "phmsa-hazmat" },
  ),
  q(
    H,
    "A fire involving explosives is usually handled by:",
    [
      "Fighting it with water from the truck tank",
      "Getting away and letting firefighters handle it — cargo fires in explosives are not a handheld-extinguisher job",
      "Driving to the nearest body of water",
      "Covering it with a tarp",
    ],
    1,
    "You do not fight a Class 1 cargo fire with a 5-B:C bottle. Distance and professionals. Engine-compartment fires on a non-explosive truck are a different, smaller problem.",
    { tags: ["hazmat"], isFree: false },
  ),
  q(
    H,
    "Parking a vehicle with Division 1.1, 1.2 or 1.3 explosives is tightly limited. You generally must not park:",
    [
      "On the shipper's approved lot",
      "On the shoulder of a major highway just to eat, or within prescribed distances of bridges, tunnels and occupied buildings unless the rules allow it",
      "At a truck stop designed for hazmat",
      "Anywhere the GPS suggests",
    ],
    1,
    "Explosives parking rules exist so a blast does not take a bridge or a restaurant. Safe havens and carrier instructions matter more than a convenient on-ramp.",
    { tags: ["hazmat"], isFree: false },
  ),
  q(
    H,
    "The emergency-response telephone number on shipping papers is so that:",
    [
      "You can order more freight",
      "Responders can reach someone who knows the product 24 hours a day",
      "The driver can call off work",
      "Customs can invoice the load",
    ],
    1,
    "CHEMTREC-style numbers and shipper 24-hour contacts exist for the people standing next to a leaking tank at 2 a.m. The number has to work.",
    { tags: ["hazmat"] },
  ),
  q(
    H,
    "You need a CDL with an H endorsement to operate a vehicle that:",
    [
      "Hauls any amount of any chemical, including a quart of windshield fluid in the cab",
      "Requires hazardous-materials placards",
      "Has a tank-shaped body with water only",
      "Tows a car on a dolly",
    ],
    1,
    "The trigger is a placarded load (and some other HM quantities in the regulations). Everyday windshield fluid in the tractor is not a placarded shipment. Water in a tanker is an N question, not H.",
    { difficulty: "EASY", tags: ["hazmat"] },
  ),
  q(
    H,
    "If shipping papers, placards and the load do not match, you should:",
    [
      "Leave anyway so you are not late",
      "Not drive the load until the shipper and carrier fix it",
      "Cover the placards with tape",
      "Write a new proper shipping name in pencil",
    ],
    1,
    "Accepting a mismatch is how citations and crashes become criminal. Stop, call, wait. Drivers get fined for rolling.",
    { tags: ["hazmat"] },
  ),

  // ------------------------------------------------------------------ TANKER
  q(
    N,
    "Liquid surge in a tank trailer is most dangerous because it can:",
    [
      "Cool the brakes",
      "Push the truck forward in a stop or shove it sideways in a curve after you think you have control",
      "Increase fuel economy",
      "Only happens in baffled tanks",
    ],
    1,
    "The liquid keeps moving after the tank shell stops. A hard brake then a release can shove you into the intersection. Surge is worse in unbaffled tanks.",
    { difficulty: "EASY", tags: ["tanker"] },
  ),
  q(
    N,
    "Baffles in a tank primarily reduce surge:",
    [
      "Side to side",
      "Front to back",
      "Up and down only",
      "They eliminate all surge",
    ],
    1,
    "Baffles are crosswise bulkheads with holes. They slow longitudinal surge. They do little for lateral surge — curves and lane changes still move the whole load sideways.",
    { tags: ["tanker"] },
  ),
  q(
    N,
    "A smoothbore (unbaffled) tank:",
    [
      "Is the most stable liquid tank",
      "Allows more front-to-back surge and is often used where the product must drain clean (food-grade)",
      "Cannot legally be used on public roads",
      "Does not need an N endorsement",
    ],
    1,
    "Smoothbore tanks are harder to drive empty-ish because the liquid is a free-moving wave. Food-grade and some chemicals need them for sanitation. Drive them even more smoothly.",
    { tags: ["tanker"] },
  ),
  q(
    N,
    "Outage is:",
    [
      "Time the driver is unpaid",
      "Empty space left in a tank for liquid expansion",
      "The amount of product that leaked",
      "A type of baffle",
    ],
    1,
    "Liquids expand with heat. Filling to the brim is how tanks burst or vent product on a hot afternoon. The shipper sets outage; the driver should not top off past the marked capacity.",
    { tags: ["tanker"] },
  ),
  q(
    N,
    "Tank vehicles have a high center of gravity, so you should:",
    [
      "Take curves and ramps slower than you would in a dry van of the same weight",
      "Always exceed the posted ramp speed to keep the liquid back",
      "Disable ABS if equipped",
      "Fill every compartment unequally on purpose",
    ],
    0,
    "A tall, partially filled tank rolls easier than a van. Posted ramp speeds are for cars. Smooth steering, early brakes, no last-second lane hops.",
    { difficulty: "EASY", tags: ["tanker"] },
  ),
  q(
    N,
    "When starting or stopping a tank, you should:",
    [
      "Brake as late and as hard as possible",
      "Accelerate and brake smoothly so you do not throw the liquid",
      "Pump the brakes to mix the product",
      "Use only the trailer hand valve",
    ],
    1,
    "Smooth inputs keep surge small. A stab stop at a light can send the wave through the bulkhead and push you into the crosswalk.",
    { tags: ["tanker"] },
  ),
  q(
    N,
    "Manhole covers and valves on a loaded tank should be:",
    [
      "Left loose so the tank can breathe freely on the highway",
      "Closed and secured as required so product and vapor stay in the tank",
      "Removed for weigh stations",
      "Wired open in winter",
    ],
    1,
    "An unsecured dome lid is a leak and a vapor release. Pre-trip includes walking the catwalk (safely) and checking closures.",
    { tags: ["tanker", "inspection"] },
  ),
  q(
    N,
    "An emergency valve on a cargo tank:",
    [
      "Is decorative",
      "Lets you shut off flow from a distance if a hose or piping fails",
      "Replaces the CDL parking brake",
      "Is only for gasoline, never diesel",
    ],
    1,
    "Remote shutoffs exist so a loading-rack fire or a sheared fitting does not empty the tank. Know where they are before you hook a hose.",
    { tags: ["tanker"], isFree: false },
  ),
  q(
    N,
    "A partially loaded tank can be harder to handle than a full one because:",
    [
      "Surge is often worse when the liquid has room to move",
      "The brakes stop working",
      "GVWR no longer applies",
      "ABS cannot be used",
    ],
    0,
    "A full tank has less wave room. A half tank is a battering ram inside the shell. Drive the partial load as if it were the more dangerous one.",
    { tags: ["tanker"] },
  ),
  q(
    N,
    "The N endorsement is about tank vehicles. You still need the H endorsement as well when:",
    [
      "The tank is empty and purged",
      "The cargo is a placarded hazardous material",
      "You are bobtailing to the shop",
      "The tank carries only potable water and the state does not treat it as a tank vehicle",
    ],
    1,
    "N is how the liquid moves. H is what the liquid is. Gasoline in a cargo tank is a classic X (N+H) combination. Water may be N-only, depending on the vehicle definition in that state.",
    { tags: ["tanker", "hazmat"] },
  ),

  // ------------------------------------------------------------------ PASSENGER
  q(
    P,
    "A passenger (P) endorsement is required for a vehicle designed to transport:",
    [
      "8 or more including the driver",
      "16 or more including the driver",
      "Any van with two rows of seats",
      "Only school children",
    ],
    1,
    "Sixteen including the driver is the federal P trigger when the vehicle is designed for that capacity. School buses also need S. A 12-passenger van is not automatically P.",
    { difficulty: "EASY", tags: ["passenger"] },
  ),
  q(
    P,
    "At a railroad crossing, a passenger bus that is required to stop should stop:",
    [
      "On the tracks so occupants can see",
      "Between 15 and 50 feet from the nearest rail, look and listen, then cross without shifting",
      "1000 feet away and then roll through in high gear",
      "Only if lights are flashing",
    ],
    1,
    "Same 15–50 foot window as other required stops. Do not change gears on the crossing. Doors and noise: follow the method that lets you actually hear a train.",
    { tags: ["passenger", "railroad"] },
  ),
  q(
    P,
    "If a bus is on fire, the priority is:",
    [
      "Saving the luggage first",
      "Stopping in a safe place and evacuating riders",
      "Reaching the next stop on the schedule",
      "Opening the fuel-fill door",
    ],
    1,
    "People out, then equipment. Know which exits work, pull over where riders will not step into traffic, and account for everyone — including riders who need help.",
    { difficulty: "EASY", tags: ["passenger"] },
  ),
  q(
    P,
    "Standee riders (where allowed) must stay:",
    [
      "Anywhere including the stairwell in the doorway",
      "Behind the standee line so they are not in the driver's workspace or the stepwell",
      "On the bumper",
      "In the luggage bays",
    ],
    1,
    "The standee line exists so you can see, steer and use the door. People in the stairwell go under the wheels in a sudden stop.",
    { tags: ["passenger"] },
  ),
  q(
    P,
    "Baggage and freight on a bus must be:",
    [
      "Piled in the aisle so it is easy to grab",
      "Secured so it cannot become a projectile or block an exit",
      "Held in riders' laps only if it is over 50 lb",
      "Stored on the dashboard",
    ],
    1,
    "Unsecured luggage is cargo in a crash. Aisles and emergency exits have to stay clear. That is a knowledge-test item and a real-world injury pattern.",
    { tags: ["passenger"] },
  ),
  q(
    P,
    "Refueling a bus with passengers aboard is:",
    [
      "Always required so you do not lose time",
      "Avoided — get riders off unless a true emergency forces a different call",
      "Legal if you keep the engine at high idle",
      "Required by FMCSA every 100 miles",
    ],
    1,
    "Fuel vapor plus a crowd is a bad mix. Standard practice is riders off, engine off, no smoking. Do not treat a pump as a rest stop with people still in the seats.",
    { tags: ["passenger"] },
  ),
  q(
    P,
    "While the bus is moving, conversation with riders should be:",
    [
      "A full tour-guide running commentary regardless of traffic",
      "Limited so it does not distract you from the road",
      "Conducted through a handheld phone passed down the aisle",
      "Replaced by texting the group chat",
    ],
    1,
    "You are still the driver of a CMV. Brief operational talk is fine; turning around to argue a fare in traffic is how buses hit parked cars.",
    { difficulty: "EASY", tags: ["passenger"] },
  ),
  q(
    P,
    "Drawbridges that do not have a traffic light or attendant generally require a bus to:",
    [
      "Never cross them",
      "Stop, make sure the bridge is completely closed, then proceed",
      "Speed up to beat the opening",
      "Cross in reverse",
    ],
    1,
    "A bus (and some other CMVs) must stop at certain drawbridges. Confirm the span is down. Yellow lights and attendants change the rule — know the local exception, but the test still expects the stop when there is no signal.",
    { tags: ["passenger"], isFree: false },
  ),
  q(
    P,
    "If you must evacuate a bus, you should:",
    [
      "Leave riders to find their own way without instruction",
      "Use available exits, give clear instructions, and move people to a safe location away from traffic and fire",
      "Keep everyone in their seats until police arrive even if the bus is filling with smoke",
      "Evacuate only the front half",
    ],
    1,
    "Assign exits, help anyone who cannot self-evacuate, and get the group off the roadway. Sitting tight through heavy smoke is how people die in their seats.",
    { tags: ["passenger"] },
  ),
  q(
    P,
    "School bus operation typically requires:",
    [
      "Only a Class C auto license",
      "A CDL with both a P endorsement and an S (school bus) endorsement",
      "Only the tanker test",
      "No medical certificate",
    ],
    1,
    "S is on top of P. This CertReady bank covers P knowledge, not the extra school-bus test (stop-arm, loading, crossing control). Do not show up for an S skills test with only General Knowledge.",
    { tags: ["passenger"] },
  ),
];
