/**
 * Additional original EPA 608 practice questions.
 * Not actual exam items. Appended by seed when the prompt is not already in the bank.
 */
import type { SeedQuestion } from "./epa-608";

const C = "core";
const T1 = "type-1";
const T2 = "type-2";
const T3 = "type-3";

const q = (
  category: string,
  prompt: string,
  options: [string, string, string, string],
  correctIndex: 0 | 1 | 2 | 3,
  explanation: string,
  extra: Partial<Omit<SeedQuestion, "category" | "prompt" | "options" | "explanation">> = {},
): SeedQuestion => ({
  category,
  prompt,
  options: options.map((text, i) => ({ label: "ABCD"[i], text, correct: i === correctIndex })),
  explanation,
  difficulty: "MEDIUM",
  isFree: true,
  ...extra,
});

export const moreEpa608Questions: SeedQuestion[] = [
  // ------------------------------------------------------------------ CORE
  q(
    C,
    "Ozone depletion potential (ODP) and global warming potential (GWP) measure:",
    [
      "The same thing — how much a refrigerant damages the ozone layer",
      "ODP measures ozone damage; GWP measures heat-trapping in the atmosphere",
      "How toxic a refrigerant is to technicians",
      "How quickly a refrigerant leaks from a fitting",
    ],
    1,
    "ODP is a chlorine/ozone issue. GWP is a climate issue (how much heat a gas traps compared with CO₂). HFCs have zero ODP but can have high GWP. Both numbers show up on Core questions.",
    { tags: ["ozone", "gwp"], source: "epa-608-overview" },
  ),
  q(
    C,
    "HFO refrigerants (such as R-1234yf) are used as replacements in part because they typically have:",
    [
      "High ODP and high GWP",
      "Zero ODP and much lower GWP than the HFCs they replace",
      "The same ozone impact as CFCs",
      "No flammability classification",
    ],
    1,
    "Hydrofluoroolefins contain no chlorine (ODP of zero) and break down faster in the atmosphere, so their GWP is far lower than older HFCs. Some are mildly flammable (A2L), which is a safety topic, not an ozone topic.",
    { tags: ["refrigerants"], difficulty: "HARD" },
  ),
  q(
    C,
    "A disposable (non-refillable) refrigerant cylinder:",
    [
      "May be refilled once if it still holds pressure",
      "Must never be used to store recovered refrigerant and must not be refilled",
      "Is the preferred container for shipping recovered R-22",
      "Can be used for recovery if it is painted gray and yellow",
    ],
    1,
    "Disposable cylinders are for virgin refrigerant only. Recovered refrigerant belongs in a DOT-approved refillable recovery cylinder (gray body, yellow top). Refilling a disposable cylinder is a DOT violation.",
    { tags: ["shipping", "cylinders"] },
  ),
  q(
    C,
    "The SNAP program (Significant New Alternatives Policy) is EPA's process for:",
    [
      "Issuing technician wallet cards",
      "Evaluating substitute refrigerants and deciding which uses are acceptable",
      "Setting DOT cylinder hydrostatic test dates",
      "Calculating the 80% fill limit",
    ],
    1,
    "SNAP lists which substitutes may be used in which end-uses. Core expects you to know that not every HFC or HFO is legal in every type of equipment, even if it has zero ODP.",
    { tags: ["regulations"], difficulty: "HARD", isFree: false },
  ),
  q(
    C,
    "If a technician knowingly vents refrigerant, EPA may:",
    [
      "Only issue a warning letter",
      "Assess substantial fines and revoke the technician's Section 608 certification",
      "Require the technician to retake Type I only",
      "Convert the certification to Type I automatically",
    ],
    1,
    "Section 608 violations can bring civil penalties (inflation-adjusted, often tens of thousands of dollars per day) and can cost a technician their certification. 'I was in a hurry' is not a defense.",
    { tags: ["regulations", "venting"] },
  ),
  q(
    C,
    "Self-contained recovery equipment:",
    [
      "Uses only the appliance compressor to move refrigerant",
      "Has its own compressor (or equivalent) and does not rely on the appliance to recover refrigerant",
      "May be used only on small appliances",
      "Is another name for a piercing valve",
    ],
    1,
    "Self-contained (active) recovery machines have their own pump. System-dependent (passive) devices rely on the appliance's compressor or pressure and are limited to appliances with 15 lb or less of refrigerant.",
    { tags: ["recovery"] },
  ),
  q(
    C,
    "Before using a recovery machine on a system with an unknown refrigerant, a technician should:",
    [
      "Assume it is R-22 and proceed",
      "Identify the refrigerant so recovered gas is not mixed and the correct recovery cylinder is used",
      "Vent a sample so it can be smelled",
      "Add nitrogen until the pressure matches R-410A",
    ],
    1,
    "Mixing refrigerants in a recovery cylinder can make the contents unrestorable and is a disposal problem. Use the nameplate, a refrigerant identifier, or both. Never mix recovered refrigerants.",
    { tags: ["recovery", "refrigerants"] },
  ),
  q(
    C,
    "The service aperture or process stub on a hermetic system is used to:",
    [
      "Vent residual refrigerant at the end of the job",
      "Install gauges, recover refrigerant and charge the system",
      "Add oil without recovering",
      "Bypass the compressor during start-up",
    ],
    1,
    "Hermetic systems are accessed through a process stub or service port. That is how you attach recovery equipment, evacuate and charge. It is not a vent.",
    { tags: ["recovery"], difficulty: "EASY" },
  ),
  q(
    C,
    "When recovering refrigerant, hoses should:",
    [
      "Be as long as possible so they stay cool",
      "Have shutoff valves and be as short as practical to limit the refrigerant left in the hoses",
      "Be purged into the room before connecting",
      "Be used without schrader depressors so they do not leak",
    ],
    1,
    "Short hoses with low-loss fittings / shutoff valves keep de minimis releases small and speed recovery. Purging hoses into the atmosphere is venting.",
    { tags: ["recovery"] },
  ),
  q(
    C,
    "A deep vacuum is pulled on a system after repair primarily to:",
    [
      "Cool the compressor motor",
      "Remove air and moisture (dehydrate) before charging",
      "Raise the refrigerant's GWP",
      "Satisfy a DOT shipping rule",
    ],
    1,
    "Evacuation boils remaining moisture at room temperature so it can be pumped out. Air left in the system becomes a non-condensable and raises head pressure. Core treats dehydration as a safety and reliability step, not a formality.",
    { tags: ["evacuation"], difficulty: "EASY" },
  ),

  // ------------------------------------------------------------------ TYPE I
  q(
    T1,
    "Which of the following is a small appliance under EPA rules?",
    [
      "A rooftop packaged unit charged with 12 lb of R-410A in the field",
      "A household refrigerator factory-charged with 6 oz of refrigerant and hermetically sealed",
      "A supermarket rack with 400 lb of R-404A",
      "A centrifugal chiller using R-123",
    ],
    1,
    "Small appliance = fully manufactured, factory-charged, hermetically sealed, 5 lb or less. Field-charged split and rooftop systems are Type II, even when the charge is modest.",
    { tags: ["small-appliances"], difficulty: "EASY" },
  ),
  q(
    T1,
    "Recovery equipment manufactured after November 15, 1993 that is used on small appliances must be:",
    [
      "Able to recover 99% of the charge in five minutes",
      "Certified to EPA's recovery standard (AHRI 740) and capable of meeting the 80%/90% or 4 in. Hg rules",
      "Open-drive and water cooled",
      "Painted red so it is not used on Type II systems",
    ],
    1,
    "Post-11/15/93 recovery equipment has to be certified. On small appliances it must actually achieve 90% with a working compressor, 80% with a dead compressor, or 4 in. Hg vacuum.",
    { tags: ["recovery", "dates"] },
  ),
  q(
    T1,
    "System-dependent (passive) recovery on a small appliance with a non-operating compressor often requires:",
    [
      "Recovering from the high side only",
      "Accessing both the high and low sides so trapped liquid can be recovered",
      "Heating the compressor with a torch",
      "Adding compressed air to push refrigerant out",
    ],
    1,
    "With the compressor dead, refrigerant can be trapped as liquid. Capturing both sides (and sometimes warming the cabinet) is how you actually hit 80%. A torch on the compressor is unsafe.",
    { tags: ["recovery", "passive"] },
  ),
  q(
    T1,
    "Piercing-type access valves on small appliances:",
    [
      "Are the preferred permanent service port and should be left on for the life of the unit",
      "Tend to leak and should not be left on as a permanent fitting after the repair",
      "Are required by EPA on every refrigerator",
      "Replace the need to recover refrigerant",
    ],
    1,
    "Saddle / piercing valves are a temporary way to get on a sealed system. They leak over time, so they are not a substitute for a proper service port if the appliance will stay in service.",
    { tags: ["small-appliances"] },
  ),
  q(
    T1,
    "If a small appliance is being disposed of and the refrigerant has already leaked out to the point that the pressure is atmospheric:",
    [
      "You may still need to recover remaining refrigerant; do not assume the system is empty until you recover or verify",
      "You can smash the compressor open and throw it in the dumpster",
      "Venting the last few ounces is always legal",
      "Only Type II technicians may handle it",
    ],
    0,
    "Disposal still requires recovery of remaining refrigerant. A flat gauge reading is not automatic permission to skip recovery — oil and cold spots can hide leftover refrigerant. Document the recovery.",
    { tags: ["disposal"], difficulty: "HARD" },
  ),
  q(
    T1,
    "Hydrocarbon refrigerants (R-600a, R-290) used in some household refrigerators:",
    [
      "Are unregulated, so venting is always allowed",
      "Are flammable; recovery is still required and equipment/cylinders must be compatible with flammable gas",
      "Have very high ODP",
      "May only be recovered by Type III technicians",
    ],
    1,
    "Isobutane and propane have zero ODP and low GWP, but they are flammable. Section 608 still prohibits knowing venting of most refrigerants. Treat them as a fire hazard: no open flame, spark-free recovery, correct cylinder.",
    { tags: ["refrigerants", "safety"], difficulty: "HARD", isFree: false },
  ),
  q(
    T1,
    "When recovering from a room air conditioner, the first step after identifying the refrigerant is usually to:",
    [
      "Cut the process tube open to the air",
      "Install an approved access fitting, connect certified recovery equipment, and recover to the required level",
      "Add nitrogen until the pressure is 150 psig",
      "Run the unit for two hours to warm the charge, then vent",
    ],
    1,
    "Access, recover, then repair or dispose. Cutting the process tube open without recovery is venting. Nitrogen at 150 psig is far too high for a small appliance leak test.",
    { tags: ["recovery"], difficulty: "EASY" },
  ),
  q(
    T1,
    "A Type I certification by itself authorizes a technician to service:",
    [
      "Any air-conditioning equipment, including chillers",
      "Only small appliances (factory-sealed, 5 lb or less)",
      "Motor vehicle air conditioning under Section 609",
      "High-pressure split systems up to 5 tons",
    ],
    1,
    "Type I is small appliances only. Split systems, rooftops and walk-ins are Type II. Chillers are Type III. Cars are Section 609. Universal is Core plus I, II and III.",
    { tags: ["certification"], difficulty: "EASY" },
  ),
  q(
    T1,
    "If the nameplate charge on a domestic refrigerator is 4 oz and the compressor is running, you must recover:",
    [
      "Nothing — charges under 1 lb are exempt",
      "90% of the charge, or evacuate to 4 in. Hg",
      "50% of the charge",
      "Only the oil",
    ],
    1,
    "There is no 'tiny charge' exemption. Working compressor → 90% or 4 in. Hg. Dead compressor → 80% or 4 in. Hg. Same rule at 4 oz as at 5 lb.",
    { tags: ["recovery"] },
  ),
  q(
    T1,
    "Filling a recovery cylinder from a small appliance should be done:",
    [
      "By watching cylinder pressure only",
      "By weight, never exceeding 80% of the cylinder's rated capacity",
      "Until liquid comes out the relief valve",
      "Until the cylinder is warm to the touch",
    ],
    1,
    "Always use a scale. Pressure does not tell you how full a cylinder is, and filling until the relief valve lifts is how cylinders rupture. The 80% fill limit is a Core rule that Type I still tests.",
    { tags: ["cylinders"] },
  ),
  q(
    T1,
    "After November 15, 1993, technicians recovering from small appliances generally must use:",
    [
      "Any vacuum pump from a hardware store",
      "Recovery equipment certified to meet EPA's performance standards",
      "Only system-dependent bags",
      "A garden hose as a liquid line",
    ],
    1,
    "The 1993 date is when recovery gear had to be certified. Using an uncertified pump and claiming 90% recovery will not satisfy an inspector — or the exam.",
    { tags: ["dates", "recovery"] },
  ),
  q(
    T1,
    "A vending machine with a factory charge of 1.5 lb of R-134a is being replaced. The technician:",
    [
      "May cut the lines and let the charge escape because it is under 5 lb",
      "Must recover the refrigerant before the appliance is disposed of",
      "Needs a Type III card because vending machines are low-pressure",
      "Should add R-22 to push the R-134a out",
    ],
    1,
    "Disposal recovery applies to small appliances. Mixing refrigerants to 'push' a charge is both venting and contamination. Vending machines are Type I, not Type III.",
    { tags: ["disposal"], isFree: false },
  ),
  q(
    T1,
    "Self-contained recovery equipment used on a small appliance with a working compressor must be capable of recovering:",
    [
      "60% of the nameplate charge",
      "90% of the charge, or pulling 4 in. Hg vacuum",
      "25 mm Hg absolute",
      "15 in. Hg vacuum",
    ],
    1,
    "Do not mix Type I numbers with Type II/III vacuums. Small appliance with running compressor: 90% or 4 in. Hg. 25 mm Hg absolute is the low-pressure (Type III) major-repair level.",
    { tags: ["recovery"] },
  ),

  // ------------------------------------------------------------------ TYPE II
  q(
    T2,
    "Leak-repair rules in 40 CFR 82.157 apply to comfort cooling, commercial refrigeration and industrial process refrigeration appliances that contain:",
    [
      "Any amount of refrigerant",
      "50 pounds or more of an ozone-depleting refrigerant or a listed substitute",
      "Only CFC refrigerants",
      "Only appliances manufactured before 1993",
    ],
    1,
    "The 50 lb threshold is the gate. Below that, the full leak-rate / repair-deadline program does not apply the same way. The current rule covers ODS and many substitute refrigerants, not just CFCs.",
    { tags: ["leak-repair"], source: "epa-leak-repair" },
  ),
  q(
    T2,
    "The current leak-rate threshold that triggers repair for comfort cooling appliances with 50 lb or more is:",
    ["30% per year", "20% per year", "10% per year", "5% per year"],
    2,
    "Comfort cooling (office AC, rooftop comfort units) is 10%. Commercial refrigeration is 20%. Industrial process refrigeration is 30%. Mixing those three numbers is the most common Type II miss.",
    { tags: ["leak-repair"], source: "epa-leak-repair" },
  ),
  q(
    T2,
    "The leak-rate threshold for commercial refrigeration appliances with 50 lb or more is:",
    ["10% per year", "20% per year", "35% per year", "50% per year"],
    1,
    "Commercial refrigeration (supermarkets, walk-ins used to store cold product) is 20% per year. The older 35% figure is outdated and will be marked wrong.",
    { tags: ["leak-repair"], source: "epa-leak-repair", isFree: false },
  ),
  q(
    T2,
    "The leak-rate threshold for industrial process refrigeration (IPR) with 50 lb or more is:",
    ["10% per year", "20% per year", "30% per year", "35% per year"],
    2,
    "IPR — equipment used in manufacturing or industrial processes, not comfort cooling — is 30%. Comfort cooling is the strictest of the three (10%).",
    { tags: ["leak-repair"], source: "epa-leak-repair" },
  ),
  q(
    T2,
    "When recovering from a Type II system with a receiver, recovery is fastest if you:",
    [
      "Start by recovering vapor from the suction line only",
      "Recover liquid first from the liquid line / receiver, then finish with vapor",
      "Vent liquid and recover only vapor",
      "Add oxygen to push liquid into the recovery cylinder",
    ],
    1,
    "Liquid recovery moves mass much faster than vapor. After the liquid is out, recover remaining vapor to the required vacuum. Never use oxygen.",
    { tags: ["recovery"] },
  ),
  q(
    T2,
    "Non-condensables (air) left in a Type II system after charging typically cause:",
    [
      "Abnormally low head pressure and icing at the compressor",
      "High head pressure, higher than the P/T chart predicts for the condenser temperature",
      "A drop in oil viscosity only",
      "The refrigerant to change chemical type",
    ],
    1,
    "Air sits in the condenser, takes up surface area, and drives discharge pressure up. Compare standing pressure to a P/T chart at a known temperature to spot non-condensables.",
    { tags: ["service"] },
  ),
  q(
    T2,
    "After a compressor burnout on a Type II system, the technician should:",
    [
      "Recharge immediately on top of the acid",
      "Recover the contaminated refrigerant, flush/replace driers, and evacuate thoroughly before charging with clean refrigerant",
      "Vent the charge so acid does not enter the recovery machine",
      "Switch the system to hydrocarbon refrigerant",
    ],
    1,
    "Burnouts leave acid and carbon. Recover (using protection on the recovery machine), replace filter-driers, evacuate, then charge. Venting a burnout is still venting.",
    { tags: ["service"], difficulty: "HARD" },
  ),
  q(
    T2,
    "For a high-pressure appliance using a refrigerant other than R-22, with a charge of 200 lb or more, recovery equipment manufactured after November 15, 1993 must evacuate to:",
    ["0 in. Hg", "4 in. Hg", "10 in. Hg", "15 in. Hg"],
    3,
    "Memorize the table: other high-pressure, ≥ 200 lb, post-1993 equipment → 15 in. Hg. R-22 at that charge is 10 in. Hg. Very-high-pressure refrigerants (R-13, R-23, R-503) are 0 in. Hg.",
    { tags: ["evacuation"], source: "epa-evacuation", difficulty: "HARD", isFree: false },
  ),
  q(
    T2,
    "R-410A service on a split system is a Type II job. Compared with R-22, R-410A:",
    [
      "Operates at substantially higher pressure and uses POE oil; recovery cylinders and gauges must be rated for it",
      "Is a drop-in that uses mineral oil and the same gauges",
      "Is a low-pressure refrigerant like R-11",
      "May be vented because it has zero ODP",
    ],
    0,
    "Zero ODP does not mean you may vent it. R-410A runs at much higher pressure than R-22, needs POE oil, and must be recovered into a compatible cylinder. It is Type II, not Type III.",
    { tags: ["refrigerants"] },
  ),
  q(
    T2,
    "If an owner of a 50+ lb comfort-cooling appliance exceeds the leak-rate threshold and cannot repair within 30 days, one lawful option is to:",
    [
      "Keep adding refrigerant indefinitely",
      "Mothball the appliance (shut down and recover the charge) or retire/replace it on EPA's timeline",
      "Switch the unit to Type I classification",
      "File nothing and wait for the next season",
    ],
    1,
    "The repair clock can be paused by mothballing (recovering to the required level and shutting down) or the owner can retire the appliance. Silently topping off is how shops get fined.",
    { tags: ["leak-repair"], difficulty: "HARD" },
  ),
  q(
    T2,
    "A split-system condensing unit that was field-charged with 8 lb of R-410A is which EPA 608 type?",
    [
      "Type I, because the charge is under 15 lb",
      "Type II — it is not a factory-sealed small appliance",
      "Type III, because 410A is high pressure",
      "Section 609",
    ],
    1,
    "The 5 lb small-appliance definition requires factory charge and a hermetic factory seal. Field-charged splits are Type II regardless of a modest charge. High pressure ≠ Type III.",
    { tags: ["certification"], difficulty: "EASY" },
  ),

  // ------------------------------------------------------------------ TYPE III
  q(
    T3,
    "Low-pressure chillers run in a vacuum on the low side. The practical leak implication is:",
    [
      "Leaks only push refrigerant out, never draw air in",
      "Leaks on the low side draw air and moisture in; a running purge unit is a leak clue",
      "Vacuum operation makes leak testing unnecessary",
      "Rupture discs are optional",
    ],
    1,
    "Below atmospheric pressure, a leak sucks air in. That is why Type III spends so much time on purge units, non-condensables and leak testing under slight positive pressure.",
    { tags: ["leak-repair", "purge"], difficulty: "EASY" },
  ),
  q(
    T3,
    "When leak-testing a low-pressure chiller, the system should not be pressurized above:",
    ["1 psig", "10 psig", "15 psig", "150 psig"],
    1,
    "Stay at or below about 10 psig. The rupture disc is typically set at 15 psig; exceeding 10 psig risks lifting the disc and dumping the charge.",
    { tags: ["leak-repair", "safety"] },
  ),
  q(
    T3,
    "The rupture disc on a low-pressure chiller is typically set to relieve at:",
    ["4 in. Hg", "10 psig", "15 psig", "150 psig"],
    2,
    "15 psig is the standard Type III number. Know it next to the 10 psig leak-test limit and the 25 mm Hg absolute evacuation level.",
    { tags: ["safety"], difficulty: "EASY" },
  ),
  q(
    T3,
    "To speed recovery from a low-pressure chiller, a technician may:",
    [
      "Heat the refrigerant with an open flame at the evaporator",
      "Raise the temperature of the water in the tubes and/or use a heater on the recovery unit, staying within safe pressures",
      "Add compressed air to the shell",
      "Bypass the rupture disc",
    ],
    1,
    "Warmer water in the tubes drives refrigerant out of the oil and liquid without creating an uncontrolled pressure spike. Open flame and compressed air are unsafe.",
    { tags: ["recovery"] },
  ),
  q(
    T3,
    "When charging a low-pressure chiller, vapor is introduced first so that:",
    [
      "The oil pump primes faster",
      "Pressure/temperature stays above freezing and water in the tubes does not freeze",
      "The rupture disc is tested",
      "GWP of the charge is reduced",
    ],
    1,
    "Liquid refrigerant flashing in an evacuated chiller can freeze water in the tubes and crack them. Charge vapor until saturation is safely above 32°F, then finish with liquid.",
    { tags: ["charging"] },
  ),
  q(
    T3,
    "Oil taken from a low-pressure chiller is often heated before disposal or handling because:",
    [
      "EPA requires oil to be boiled",
      "Refrigerant is dissolved in the oil and heating drives it out so it can be recovered",
      "Heating converts R-123 into R-22",
      "It reduces the ODP of leftover refrigerant",
    ],
    1,
    "Low-pressure refrigerant hides in oil. Warm the oil, recover the refrigerant that comes off, then handle the oil. Dumping cold oil can vent dissolved refrigerant.",
    { tags: ["recovery", "oil"], isFree: false },
  ),
  q(
    T3,
    "For a low-pressure appliance using recovery equipment manufactured after November 15, 1993, the required evacuation level before a major repair is:",
    ["0 in. Hg", "10 in. Hg", "25 mm Hg absolute", "4 in. Hg"],
    2,
    "25 mm Hg absolute (about 1 in. Hg absolute, i.e. a deep vacuum) is the Type III number for post-1993 equipment. Older equipment used 25 in. Hg vacuum. Do not confuse mm Hg absolute with inches of mercury vacuum.",
    { tags: ["evacuation"], source: "epa-evacuation" },
  ),
  q(
    T3,
    "A purge unit on a low-pressure chiller is designed to:",
    [
      "Add make-up refrigerant automatically",
      "Remove non-condensable gases (mostly air) from the condenser",
      "Replace the rupture disc",
      "Recover oil from the evaporator",
    ],
    1,
    "Purge units extract air that leaked in. Frequent purge operation means the machine is leaking inward. The purge is not a refrigerant pump-out unit.",
    { tags: ["purge"], difficulty: "EASY" },
  ),
  q(
    T3,
    "Water tubes in a chiller evaporator can freeze during charging or recovery if:",
    [
      "The cooling tower fan is off",
      "Liquid refrigerant is dumped into an evacuated machine so saturation temperature falls below 32°F",
      "The purge unit is dirty",
      "POE oil is used",
    ],
    1,
    "That is why vapor-first charging exists. Frozen tubes are an expensive Type III mistake and a favorite exam scenario.",
    { tags: ["charging", "safety"] },
  ),
  q(
    T3,
    "ASHRAE Standard 15 machinery-room rules matter on Type III jobs because chillers:",
    [
      "Use flammable hydrocarbons exclusively",
      "Can dump a large charge that displaces oxygen; rooms need monitors, ventilation and outdoor relief venting",
      "Never leak",
      "Are exempt from building codes",
    ],
    1,
    "A centrifugal chiller holds hundreds of pounds. A rupture disc that vents indoors can asphyxiate people. Relief must terminate outdoors; refrigerant monitors and ventilation are required.",
    { tags: ["safety"] },
  ),
  q(
    T3,
    "Type III certification by itself authorizes work on:",
    [
      "Window air conditioners and domestic refrigerators",
      "Low-pressure appliances such as centrifugal chillers",
      "Motor vehicle A/C",
      "Any high-pressure split system",
    ],
    1,
    "Type III = low-pressure appliances. You still need Core. Small appliances are Type I; splits and racks are Type II. Universal covers all three.",
    { tags: ["certification"], difficulty: "EASY" },
  ),
  q(
    T3,
    "If a low-pressure chiller's rupture disc has blown, the technician should:",
    [
      "Replace the disc, then leak-test and recover remaining refrigerant as required before charging",
      "Recharge immediately through the open disc port",
      "Leave the disc off so the machine cannot overpressure",
      "Convert the machine to Type II service",
    ],
    0,
    "A blown disc is both a safety device that has done its job and a wide-open leak. Recover what is left, replace the disc with the correct rating, find why pressure went high, then charge.",
    { tags: ["safety", "leak-repair"], isFree: false },
  ),
];
